### ISSUE TITLE
new command to commit and push

### ISSUE THREAD

**Issue by Emergency1999** [Vereine-Vereint/service.core#3]
something like:

./service.sh commit <message>    Creates commits for all repositories together

- should ask the user if he changed all versions correctly!
- needs to do submodules first!
- should check all repositories, add all changes and commit with that message (only if any changes occured)
- and ask the user if he wants to push all to the server

**Comment by chrisgra** [comment]
@Emergency1999 the current structure of the service.sh does not really allow for committing changes in the outermost repo because it cd's into the directory of the service.sh script (see 
![image](https://github.com/Vereine-Vereint/service.core/assets/42114113/9866e0d6-0577-422d-bf10-a2428e4549bf)
)

This means that the commit-command only commits and optionally pushes everything starting from within the repo where the service.sh script is located (see 
![image](https://github.com/Vereine-Vereint/service.core/assets/42114113/eb0d7821-be11-4751-93ab-77f037a94b3c)
)
It committed everything for every submodule except the outermost repo (service.traefik.connecta).

Should I change it to also include the outermost repo (in this case service.traefik.connecta)? It could be done by cd-ing into the outermost repo right before this `current_working_dir=$(pwd)` line in cmd _git.sh
